/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight_on = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay_cash = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_2 = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_3 = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_3 = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty_1 = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_1 = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_1 = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled_alt = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_2 = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_1 = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_alt = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_3 = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_3 = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_1 = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_bold = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_bold = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_bold = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_bold = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_fat = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_fat = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_fat = IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_fat = IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_2 = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_3 = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_pencil = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData king = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash_1 = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_1 = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_6 = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quick_transfer = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_code = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_1 = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_2 = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_history = IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_4 = IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promotion = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_1 = IconData(0xf006, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open_1 = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_1 = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list_1 = IconData(0xf009, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb = IconData(0xf00a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty = IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow_empty = IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xf00e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xf00f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = IconData(0xf010, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = IconData(0xf011, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf012, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = IconData(0xf014, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science = IconData(0xf016, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science_inv = IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_1 = IconData(0xf018, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_inv = IconData(0xf019, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math = IconData(0xf01a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled_empty = IconData(0xf01b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled = IconData(0xf01c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_1 = IconData(0xf01d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt2 = IconData(0xf01e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt = IconData(0xf01f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_adjust = IconData(0xf020, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half_1 = IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half_empty = IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw = IconData(0xf025, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_broken = IconData(0xf028, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash = IconData(0xf029, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_1 = IconData(0xf02a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet_1 = IconData(0xf02b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xf02c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 = IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_1 = IconData(0xf02f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_3 = IconData(0xf031, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor = IconData(0xf032, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet_1 = IconData(0xf033, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_1 = IconData(0xf034, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connected_object = IconData(0xf035, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData isight = IconData(0xf039, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam_1 = IconData(0xf03a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xf03b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1 = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf03f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xf040, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xf045, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off = IconData(0xf047, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_1 = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_2 = IconData(0xf04a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble_circled = IconData(0xf04f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_circled = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf052, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt = IconData(0xf053, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled = IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf055, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt2 = IconData(0xf056, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circled = IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus_circled = IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus = IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circled = IconData(0xf05b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf05c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf05d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_circled = IconData(0xf05e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo = IconData(0xf05f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo_circled = IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_3 = IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_male = IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_female = IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_1 = IconData(0xf064, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_1 = IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xf069, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_2 = IconData(0xf06a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xf06d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xf074, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = IconData(0xf075, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_2 = IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = IconData(0xf07e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = IconData(0xf07f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xf080, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xf081, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_5 = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_2 = IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = IconData(0xf084, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xf087, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize = IconData(0xf088, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xf089, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud_circled = IconData(0xf08a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_2 = IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_empty = IconData(0xf4c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_1 = IconData(0xf4c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xf4f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_2 = IconData(0xf4f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2 = IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt = IconData(0xf510, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_3 = IconData(0xf512, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_1 = IconData(0xf513, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick = IconData(0xf514, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire_1 = IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spread = IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner1 = IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner2 = IconData(0xf529, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
